file_name1 = input("Enter file 1 name: ")
file_name2 = input("Enter file 2 name: “)
file3 = open(file_name2, "r")
c = file3.readline()
file1 = open(file_name1, "r")
file2 = open(file_name2, "w")
l = file1.readline()
print("\n\nContent in file abc before copying is:", c)
print("Content before copying in xyz is :", l)
while l:
   file2.write(l)
   print("\n content copied successfully \n")
   print("Content after copying in abc is:", l)
   l = file1.readline()
file1.close()
file2.close()
